### PR TITLE
Css fixed

### PR DESCRIPTION
**Pull request by VasilPaligorov**

### CODE REVIEW

**Comment by kiko1134** [comment]
What was the actual problem with the footer because I couldn't figure it out?

**Comment by VasilPaligorov** [comment]
> What was the actual problem with the footer because I couldn't figure it out?

In the HTML of the page  div class="content"  wasn't closed

**Comment by kiko1134** [comment]
Omg. Happy to hear that it was only the tag .What a pleasure to work with you @VasilPaligorov

**Comment by VasilPaligorov** [comment]
> Omg. Happy to hear that it was only the tag .What a pleasure to work with you @VasilPaligorov

I feel it too for you

**Pull request merged**
